// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example_service.proto

package exampleprotobuffer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("example_service.proto", fileDescriptor_bdab94845fc2b7e8) }

var fileDescriptor_bdab94845fc2b7e8 = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0x8d, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x12, 0x82, 0x0a, 0x83, 0x79, 0x49, 0xa5, 0x69, 0x69, 0xa9, 0x45, 0x52, 0xc2, 0x30,
	0xa5, 0xb9, 0xf9, 0x29, 0xa9, 0x39, 0x10, 0x85, 0x46, 0x29, 0x5c, 0xec, 0xae, 0x10, 0x61, 0xa1,
	0x48, 0x2e, 0x1e, 0xf7, 0xd4, 0x92, 0xe0, 0xfc, 0xdc, 0xd4, 0x92, 0x8c, 0xcc, 0xbc, 0x74, 0x21,
	0x65, 0x3d, 0x4c, 0x43, 0xf4, 0x90, 0x55, 0x04, 0xa5, 0x16, 0x4a, 0xa9, 0x10, 0x56, 0x54, 0x5c,
	0x90, 0xc4, 0x06, 0x96, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x6f, 0xde, 0xc3, 0xae,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExampleClient is the client API for Example service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExampleClient interface {
	GetSomething(ctx context.Context, in *GetSomethingReq, opts ...grpc.CallOption) (*GetSomethingResp, error)
}

type exampleClient struct {
	cc *grpc.ClientConn
}

func NewExampleClient(cc *grpc.ClientConn) ExampleClient {
	return &exampleClient{cc}
}

func (c *exampleClient) GetSomething(ctx context.Context, in *GetSomethingReq, opts ...grpc.CallOption) (*GetSomethingResp, error) {
	out := new(GetSomethingResp)
	err := c.cc.Invoke(ctx, "/exampleprotobuffer.Example/GetSomething", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleServer is the server API for Example service.
type ExampleServer interface {
	GetSomething(context.Context, *GetSomethingReq) (*GetSomethingResp, error)
}

// UnimplementedExampleServer can be embedded to have forward compatible implementations.
type UnimplementedExampleServer struct {
}

func (*UnimplementedExampleServer) GetSomething(ctx context.Context, req *GetSomethingReq) (*GetSomethingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSomething not implemented")
}

func RegisterExampleServer(s *grpc.Server, srv ExampleServer) {
	s.RegisterService(&_Example_serviceDesc, srv)
}

func _Example_GetSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSomethingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).GetSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/exampleprotobuffer.Example/GetSomething",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).GetSomething(ctx, req.(*GetSomethingReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Example_serviceDesc = grpc.ServiceDesc{
	ServiceName: "exampleprotobuffer.Example",
	HandlerType: (*ExampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSomething",
			Handler:    _Example_GetSomething_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example_service.proto",
}
