// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example_model.proto

package exampleprotobuffer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetSomethingReq struct {
	SomeInt64            int64    `protobuf:"varint,1,opt,name=someInt64,proto3" json:"someInt64,omitempty"`
	SomeStr              string   `protobuf:"bytes,2,opt,name=someStr,proto3" json:"someStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSomethingReq) Reset()         { *m = GetSomethingReq{} }
func (m *GetSomethingReq) String() string { return proto.CompactTextString(m) }
func (*GetSomethingReq) ProtoMessage()    {}
func (*GetSomethingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb295d4214d5af9, []int{0}
}

func (m *GetSomethingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSomethingReq.Unmarshal(m, b)
}
func (m *GetSomethingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSomethingReq.Marshal(b, m, deterministic)
}
func (m *GetSomethingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSomethingReq.Merge(m, src)
}
func (m *GetSomethingReq) XXX_Size() int {
	return xxx_messageInfo_GetSomethingReq.Size(m)
}
func (m *GetSomethingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSomethingReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetSomethingReq proto.InternalMessageInfo

func (m *GetSomethingReq) GetSomeInt64() int64 {
	if m != nil {
		return m.SomeInt64
	}
	return 0
}

func (m *GetSomethingReq) GetSomeStr() string {
	if m != nil {
		return m.SomeStr
	}
	return ""
}

type GetSomethingResp struct {
	SomeUint64           uint64   `protobuf:"varint,1,opt,name=someUint64,proto3" json:"someUint64,omitempty"`
	SomeBool             bool     `protobuf:"varint,2,opt,name=someBool,proto3" json:"someBool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSomethingResp) Reset()         { *m = GetSomethingResp{} }
func (m *GetSomethingResp) String() string { return proto.CompactTextString(m) }
func (*GetSomethingResp) ProtoMessage()    {}
func (*GetSomethingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb295d4214d5af9, []int{1}
}

func (m *GetSomethingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSomethingResp.Unmarshal(m, b)
}
func (m *GetSomethingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSomethingResp.Marshal(b, m, deterministic)
}
func (m *GetSomethingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSomethingResp.Merge(m, src)
}
func (m *GetSomethingResp) XXX_Size() int {
	return xxx_messageInfo_GetSomethingResp.Size(m)
}
func (m *GetSomethingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSomethingResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetSomethingResp proto.InternalMessageInfo

func (m *GetSomethingResp) GetSomeUint64() uint64 {
	if m != nil {
		return m.SomeUint64
	}
	return 0
}

func (m *GetSomethingResp) GetSomeBool() bool {
	if m != nil {
		return m.SomeBool
	}
	return false
}

func init() {
	proto.RegisterType((*GetSomethingReq)(nil), "exampleprotobuffer.GetSomethingReq")
	proto.RegisterType((*GetSomethingResp)(nil), "exampleprotobuffer.GetSomethingResp")
}

func init() { proto.RegisterFile("example_model.proto", fileDescriptor_6bb295d4214d5af9) }

var fileDescriptor_6bb295d4214d5af9 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0x8d, 0xcf, 0xcd, 0x4f, 0x49, 0xcd, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x12, 0x82, 0x0a, 0x82, 0x79, 0x49, 0xa5, 0x69, 0x69, 0xa9, 0x45, 0x4a, 0x9e, 0x5c, 0xfc, 0xee,
	0xa9, 0x25, 0xc1, 0xf9, 0xb9, 0xa9, 0x25, 0x19, 0x99, 0x79, 0xe9, 0x41, 0xa9, 0x85, 0x42, 0x32,
	0x5c, 0x9c, 0xc5, 0xf9, 0xb9, 0xa9, 0x9e, 0x79, 0x25, 0x66, 0x26, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0xcc, 0x41, 0x08, 0x01, 0x21, 0x09, 0x2e, 0x76, 0x10, 0x27, 0xb8, 0xa4, 0x48, 0x82, 0x49, 0x81,
	0x51, 0x83, 0x33, 0x08, 0xc6, 0x55, 0xf2, 0xe3, 0x12, 0x40, 0x35, 0xaa, 0xb8, 0x40, 0x48, 0x8e,
	0x8b, 0x0b, 0x24, 0x1d, 0x9a, 0x09, 0x37, 0x8c, 0x25, 0x08, 0x49, 0x44, 0x48, 0x8a, 0x8b, 0x03,
	0xc4, 0x73, 0xca, 0xcf, 0xcf, 0x01, 0x1b, 0xc7, 0x11, 0x04, 0xe7, 0x27, 0xb1, 0x81, 0xdd, 0x69,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x28, 0x92, 0x9c, 0xcc, 0x00, 0x00, 0x00,
}
